# JEKYLL - SITE SETTINGS

title: Maya A. Norman
email:
description: >- # this means to ignore newlines until "baseurl:" This description will appear in your document head meta (for Google search results) and in your feed.xml site description.
github_username: username
minimal_mistakes_skin: default

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-pdf-embed
  - jekyll-seo-tag

author:
  name   : " "
  avatar :  "/assets/images/fresh-kills-landfill-circa-1950.jpeg"
  #  caption : '[**Fresh Kills Landfill**](https://www.collectorsweekly.com/articles/wp-content/uploads/2013/06/fresh-kills-landfill-2b41798576e074251-709x1024.jpg){:target="_blank"} (~ 1950)'
  bio : "Me and Fresh Kills Landfill circa 1950. Photo courtesy of Collectors Weekly."
  links:
  #  - label: "Email"
  #    icon: "fas fa-fw fa-envelope"
  #    url: "mailto:man2185@columbia.edu"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/manorman5"

footer:

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      toc: false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
